-- 사용자별 커스텀 재무 데이터 테이블
create table if not exists public.user_custom_financials (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  company_code text not null,
  year integer not null,
  
  -- 사용자가 수정한 값들 (원 단위로 저장 권장)
  net_income numeric default 0, 
  equity numeric default 0,     
  op_income numeric default 0,  
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- 한 사용자가 한 기업의 특정 연도에 대해 중복 데이터 생성 방지
  unique(user_id, company_code, year)
);

-- RLS (Row Level Security) 정책 설정
alter table public.user_custom_financials enable row level security;

-- 기존 정책이 있다면 삭제 후 재생성 (중복 오류 방지)
drop policy if exists "Users can view their own custom financials" on public.user_custom_financials;
drop policy if exists "Users can insert their own custom financials" on public.user_custom_financials;
drop policy if exists "Users can update their own custom financials" on public.user_custom_financials;
drop policy if exists "Users can delete their own custom financials" on public.user_custom_financials;

create policy "Users can view their own custom financials"
  on public.user_custom_financials for select
  using (auth.uid() = user_id);

create policy "Users can insert their own custom financials"
  on public.user_custom_financials for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own custom financials"
  on public.user_custom_financials for update
  using (auth.uid() = user_id);

create policy "Users can delete their own custom financials"
  on public.user_custom_financials for delete
  using (auth.uid() = user_id);