-- 사용자별 차트 설정 (멀티플 등) 테이블
create table if not exists public.user_chart_settings (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  company_code text not null,
  band_type text not null, -- 'PER', 'PBR', 'POR'
  multipliers jsonb not null, -- [10, 15, 20] 같은 배열 저장 (text array도 가능하지만 호환성 위해 jsonb 권장)
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  unique(user_id, company_code, band_type)
);

alter table public.user_chart_settings enable row level security;

drop policy if exists "Users can view their own chart settings" on public.user_chart_settings;
drop policy if exists "Users can insert their own chart settings" on public.user_chart_settings;
drop policy if exists "Users can update their own chart settings" on public.user_chart_settings;
drop policy if exists "Users can delete their own chart settings" on public.user_chart_settings;

create policy "Users can view their own chart settings" on public.user_chart_settings for select using (auth.uid() = user_id);
create policy "Users can insert their own chart settings" on public.user_chart_settings for insert with check (auth.uid() = user_id);
create policy "Users can update their own chart settings" on public.user_chart_settings for update using (auth.uid() = user_id);
create policy "Users can delete their own chart settings" on public.user_chart_settings for delete using (auth.uid() = user_id);