-- 사용자별 관심 종목(즐겨찾기) 테이블
create table if not exists public.user_favorite_stocks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  company_code text not null,
  company_name text not null, -- 목록 표시용 (조인 없이 빠르게 보기 위해)
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- 중복 즐겨찾기 방지
  unique(user_id, company_code)
);

alter table public.user_favorite_stocks enable row level security;

drop policy if exists "Users can view their own favorites" on public.user_favorite_stocks;
drop policy if exists "Users can insert their own favorites" on public.user_favorite_stocks;
drop policy if exists "Users can delete their own favorites" on public.user_favorite_stocks;

create policy "Users can view their own favorites" on public.user_favorite_stocks for select using (auth.uid() = user_id);
create policy "Users can insert their own favorites" on public.user_favorite_stocks for insert with check (auth.uid() = user_id);
create policy "Users can delete their own favorites" on public.user_favorite_stocks for delete using (auth.uid() = user_id);