create table if not exists raw_dart_financials (
  id bigint generated by default as identity primary key,
  corp_code text not null,
  stock_code text,
  corp_name text,
  rcept_no text not null,
  bsns_year integer not null,
  reprt_code text not null,
  fs_div text not null,
  sj_div text,
  sj_nm text,
  account_id text,
  account_nm text not null,
  account_detail text,
  thstrm_nm text,
  thstrm_amount text,
  thstrm_add_amount text,
  frmtrm_nm text,
  frmtrm_amount text,
  frmtrm_add_amount text,
  bfefrmtrm_nm text,
  bfefrmtrm_amount text,
  currency text,
  raw_payload jsonb not null default '{}'::jsonb,
  raw_fetched_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create unique index if not exists idx_raw_dart_financials_unique_row
  on raw_dart_financials (
    corp_code,
    rcept_no,
    fs_div,
    coalesce(sj_div, ''),
    coalesce(account_id, ''),
    account_nm,
    coalesce(thstrm_nm, '')
  );

create index if not exists idx_raw_dart_financials_stock_period
  on raw_dart_financials (stock_code, bsns_year desc, reprt_code, fs_div);

create index if not exists idx_raw_dart_financials_rcept_no
  on raw_dart_financials (rcept_no);

create index if not exists idx_raw_dart_financials_corp_code_period
  on raw_dart_financials (corp_code, bsns_year desc, reprt_code);

alter table raw_dart_financials enable row level security;

comment on table raw_dart_financials is
  'Raw DART financial statement rows preserved per filing before normalization.';
